<a href="https://colab.research.google.com/github/lucianoyllarreta/CLASE_CIENCIA_DATOS_I/blob/main/LOS%204%20FANT%C3%81STICOS%20/%20DF.%20Ca%C3%ADda%20del%20Muro%20de%20Berl%C3%ADn%20clasificado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import files
upload  = files.upload()

Saving disuguaglianza-economica-globale-e-povert-1980-2024.csv to disuguaglianza-economica-globale-e-povert-1980-2024.csv

In [8]:
import pandas as pd
df = pd.read_csv('disuguaglianza-economica-globale-e-povert-1980-2024.csv')

In [9]:
### CLASIFICACIÓN GEOGRÁFICA DE LOS PAÍSES ###
# AMÉRICA
america_del_sur = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela']
america_central_y_caribe = ['Belize', 'Costa Rica', 'El Salvador', 'Guatemala', 'Honduras','Nicaragua', 'Panama', 'Bahamas', 'Barbados', 'Cuba', 'Dominica','Dominican Republic', 'Grenada', 'Haiti', 'Jamaica', 'Saint Kitts and Nevis','Saint Lucia', 'Saint Vincent and the Grenadines', 'Trinidad and Tobago']
america_del_norte = ['Canada', 'United States', 'Mexico']
# EUROPA
europa = ['Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina','Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland','France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy','Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Montenegro','Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania','Russia', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland','Ukraine', 'United Kingdom']

# ÁFRICA
africa = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cabo Verde','Cameroon', 'Central African Republic', 'Chad', 'Comoros', 'Congo', 'Cote d\'Ivoire','Democratic Republic of Congo', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea','Eswatini', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau','Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali','Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger','Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles','Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Tanzania','Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe']

# ASIA
asia = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan','Brunei', 'Cambodia', 'China', 'Georgia', 'India', 'Indonesia', 'Iran','Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan','Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal','North Korea', 'Oman', 'Pakistan', 'Palestine', 'Philippines', 'Qatar','Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Taiwan','Tajikistan', 'Thailand', 'Timor', 'Turkey', 'Turkmenistan','United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen']

# OCEANÍA
oceania = ['Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Micronesia (country)','Nauru', 'New Zealand', 'Palau', 'Papua New Guinea', 'Samoa','Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu']

In [10]:
# Creamos DataFrame para Caída Muro Berlín (1984-1994)
df_muro_berlin = df[(df['year'] >= 1984) & (df['year'] <= 1994)]

In [ ]:
# Filtramos América del Sur
df_muro_sur = df_muro_berlin[df_muro_berlin['country'].isin(america_del_sur)]

In [ ]:
display(df_muro_sur)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
274,Argentina,1984,ARG,29863090,3.578443e+11,11982.83,NaN,NaN,14.86,50.57,8.17
275,Argentina,1985,ARG,30336448,3.341714e+11,11015.51,NaN,NaN,14.86,50.57,8.17
276,Argentina,1986,ARG,30811982,3.586347e+11,11639.45,NaN,NaN,14.86,50.57,8.17
277,Argentina,1987,ARG,31291764,3.678936e+11,11756.88,NaN,NaN,14.86,50.57,8.17
278,Argentina,1988,ARG,31780534,3.609212e+11,11356.67,NaN,NaN,14.86,50.57,8.17
...,...,...,...,...,...,...,...,...,...,...,...
8740,Venezuela,1990,VEN,19827005,2.560785e+11,12915.64,NaN,NaN,22.27,55.41,8.39
8741,Venezuela,1991,VEN,20304898,2.821323e+11,13894.79,NaN,NaN,22.27,55.41,8.39
8742,Venezuela,1992,VEN,20780946,3.010554e+11,14487.09,6.884314,42.061281,22.27,55.41,8.39
8743,Venezuela,1993,VEN,21254525,3.032639e+11,14268.21,NaN,NaN,22.27,55.41,8.39
8744,Venezuela,1994,VEN,21725186,2.977286e+11,13704.31,NaN,NaN,22.27,55.41,8.39

In [ ]:
# Filtramos América Central y Caribe
df_muro_caribe = df_muro_berlin[df_muro_berlin['country'].isin(america_central_y_caribe)]

In [ ]:
display(df_muro_caribe)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
499,Bahamas,1984,BHS,248879,NaN,NaN,NaN,NaN,22.27,55.41,8.39
500,Bahamas,1985,BHS,253169,NaN,NaN,NaN,NaN,22.27,55.41,8.39
501,Bahamas,1986,BHS,257547,NaN,NaN,NaN,NaN,22.27,55.41,8.39
502,Bahamas,1987,BHS,261947,NaN,NaN,NaN,NaN,22.27,55.41,8.39
503,Bahamas,1988,BHS,266457,NaN,NaN,NaN,NaN,22.27,55.41,8.39
...,...,...,...,...,...,...,...,...,...,...,...
8110,Trinidad and Tobago,1990,TTO,1252215,1.771056e+10,14143.39,NaN,NaN,22.27,55.41,8.39
8111,Trinidad and Tobago,1991,TTO,1262174,1.774493e+10,14059.02,NaN,NaN,22.27,55.41,8.39
8112,Trinidad and Tobago,1992,TTO,1271681,1.803369e+10,14180.98,3.238,40.185452,22.27,55.41,8.39
8113,Trinidad and Tobago,1993,TTO,1280474,1.756534e+10,13717.84,NaN,NaN,22.27,55.41,8.39
8114,Trinidad and Tobago,1994,TTO,1288353,1.713654e+10,13301.12,NaN,NaN,22.27,55.41,8.39

In [ ]:
df_muro_norte = df_muro_berlin[df_muro_berlin['country'].isin(america_del_norte)]

In [ ]:
display(df_muro_norte)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
1354,Canada,1984,CAN,25670376,6.897335e+11,26868.85,0.999904,33.518428,7.73,29.07,22.17
1355,Canada,1985,CAN,25927463,7.270133e+11,28040.28,0.745663,33.174872,7.66,29.19,21.96
1356,Canada,1986,CAN,26211036,7.460746e+11,28464.14,0.998190,31.675813,7.81,29.65,21.11
1357,Canada,1987,CAN,26540913,7.764725e+11,29255.68,0.499682,31.653872,8.06,29.90,21.07
1358,Canada,1988,CAN,26927938,8.142401e+11,30237.74,0.749371,31.197870,8.87,30.71,20.93
1359,Canada,1989,CAN,27366046,8.339187e+11,30472.75,1.249350,31.012514,9.48,31.44,20.36
1360,Canada,1990,CAN,27789437,8.359968e+11,30083.26,1.248458,31.365356,9.27,31.61,19.86
1361,Canada,1991,CAN,28157154,8.202743e+11,29132.00,1.247662,31.943390,9.15,31.80,19.19
1362,Canada,1992,CAN,28500066,8.297421e+11,29113.69,0.746889,31.564316,9.19,31.83,18.99
1363,Canada,1993,CAN,28830635,8.537760e+11,29613.50,1.247629,31.675923,9.57,32.51,18.33
1364,Canada,1994,CAN,29147383,8.948519e+11,30700.94,0.989580,31.303805,9.61,32.68,18.21
5089,Mexico,1984,MEX,73506848,7.340585e+11,9986.26,14.954573,48.527011,12.45,54.45,6.29
5090,Mexico,1985,MEX,75043415,7.511673e+11,10009.77,NaN,NaN,12.45,54.45,6.29
5091,Mexico,1986,MEX,76585638,7.281811e+11,9508.06,NaN,NaN,12.45,54.45,6.29
5092,Mexico,1987,MEX,78136652,7.416138e+11,9491.24,NaN,NaN,12.45,54.45,6.29
5093,Mexico,1988,MEX,79695526,7.518202e+11,9433.66,NaN,NaN,12.45,54.45,6.29
5094,Mexico,1989,MEX,81247174,7.829813e+11,9637.03,14.774685,50.108999,12.45,54.45,6.29
5095,Mexico,1990,MEX,82820170,8.235775e+11,9944.17,NaN,NaN,12.45,54.45,6.29
5096,Mexico,1991,MEX,84430565,8.651487e+11,10246.87,NaN,NaN,12.45,54.45,6.29
5097,Mexico,1992,MEX,86044806,9.021083e+11,10484.17,13.321230,52.310723,12.45,54.45,6.29
5098,Mexico,1993,MEX,87653817,9.253433e+11,10556.79,NaN,NaN,12.45,54.45,6.29
5099,Mexico,1994,MEX,89259202,9.729919e+11,10900.75,13.647698,53.422207,12.45,54.45,6.29
8509,United States,1984,USA,239353967,7.581108e+12,31673.21,0.749372,37.344322,NaN,NaN,NaN
8510,United States,1985,USA,241690438,7.874872e+12,32582.47,0.749656,37.640655,NaN,NaN,NaN
8511,United States,1986,USA,243953807,8.146028e+12,33391.68,0.746845,37.556332,NaN,NaN,NaN
8512,United States,1987,USA,246161292,8.432567e+12,34256.27,0.499271,37.196100,NaN,NaN,NaN
8513,United States,1988,USA,248393236,8.787203e+12,35376.18,0.499204,37.705073,NaN,NaN,NaN
8514,United States,1989,USA,250675047,9.091292e+12,36267.24,0.499201,38.237947,NaN,NaN,NaN
8515,United States,1990,USA,253373387,9.250378e+12,36508.88,0.497143,38.262486,NaN,NaN,NaN
8516,United States,1991,USA,256471424,9.224688e+12,35967.70,0.499387,38.044837,NaN,NaN,NaN
8517,United States,1992,USA,259606021,9.552659e+12,36796.75,0.497899,38.372794,NaN,NaN,NaN
8518,United States,1993,USA,262633229,9.814940e+12,37371.28,0.748369,40.363088,NaN,NaN,NaN
8519,United States,1994,USA,265474811,1.021120e+13,38463.93,0.747120,39.985380,NaN,NaN,NaN

In [ ]:
df_muro_europa = df_muro_berlin[df_muro_berlin['country'].isin(europa)]

In [ ]:
display(df_muro_europa)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
49,Albania,1984,ALB,2964961,1.108009e+10,3737.01,NaN,NaN,6.79,30.59,19.49
50,Albania,1985,ALB,3026245,1.137146e+10,3757.61,NaN,NaN,6.79,30.59,19.49
51,Albania,1986,ALB,3087658,1.166975e+10,3779.48,NaN,NaN,6.79,30.59,19.48
52,Albania,1987,ALB,3148843,1.197530e+10,3803.08,NaN,NaN,6.79,30.59,19.49
53,Albania,1988,ALB,3212924,1.229642e+10,3827.18,NaN,NaN,6.79,30.58,19.49
...,...,...,...,...,...,...,...,...,...,...,...
8470,United Kingdom,1990,GBR,57367867,1.505692e+12,26246.27,0.218847,35.741970,9.10,32.91,19.52
8471,United Kingdom,1991,GBR,57555199,1.488075e+12,25854.75,0.226257,34.962818,9.54,33.56,19.23
8472,United Kingdom,1992,GBR,57719273,1.491752e+12,25844.96,0.240086,34.955472,9.24,33.63,19.19
8473,United Kingdom,1993,GBR,57861037,1.527509e+12,26399.61,0.241170,35.075960,9.72,34.23,18.93
8474,United Kingdom,1994,GBR,58003200,1.585373e+12,27332.51,0.246627,35.978922,9.96,34.35,19.23

In [ ]:
df_muro_africa = df_muro_berlin[df_muro_berlin['country'].isin(africa)]

In [ ]:
display(df_muro_africa)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
94,Algeria,1984,DZA,21271969,1.144067e+11,5378.28,NaN,NaN,15.72,46.60,15.08
95,Algeria,1985,DZA,22008542,1.203642e+11,5468.98,NaN,NaN,15.72,46.60,15.08
96,Algeria,1986,DZA,22745501,1.191450e+11,5238.18,NaN,NaN,15.72,46.60,15.08
97,Algeria,1987,DZA,23443627,1.183212e+11,5047.05,NaN,NaN,15.72,46.60,15.08
98,Algeria,1988,DZA,24109538,1.158217e+11,4803.98,12.263,37.356994,15.72,46.60,15.08
...,...,...,...,...,...,...,...,...,...,...,...
8920,Zimbabwe,1990,ZWE,10137287,2.193705e+10,2164.00,NaN,NaN,15.93,51.37,11.88
8921,Zimbabwe,1991,ZWE,10404820,2.318986e+10,2228.76,NaN,NaN,15.93,51.37,11.88
8922,Zimbabwe,1992,ZWE,10702697,2.113378e+10,1974.62,NaN,NaN,15.93,51.37,11.88
8923,Zimbabwe,1993,ZWE,10860285,2.140646e+10,1971.08,NaN,NaN,15.93,51.37,11.88
8924,Zimbabwe,1994,ZWE,10873146,2.344750e+10,2156.46,NaN,NaN,15.93,51.37,11.88

In [ ]:
df_muro_asia = df_muro_berlin[df_muro_berlin['country'].isin(asia)]

In [ ]:
display(df_muro_asia)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
4,Afghanistan,1984,AFG,11190222,1.707215e+10,1525.63,NaN,NaN,16.22,41.94,17.17
5,Afghanistan,1985,AFG,11426855,1.710848e+10,1497.22,NaN,NaN,16.22,41.94,17.17
6,Afghanistan,1986,AFG,11420074,1.764134e+10,1544.77,NaN,NaN,16.22,41.94,17.17
7,Afghanistan,1987,AFG,11387822,1.581082e+10,1388.40,NaN,NaN,16.22,41.94,17.17
8,Afghanistan,1988,AFG,11523299,1.449907e+10,1258.24,NaN,NaN,16.22,41.94,17.17
...,...,...,...,...,...,...,...,...,...,...,...
8830,Yemen,1990,YEM,13887863,4.497104e+10,3238.15,NaN,NaN,22.70,56.68,9.99
8831,Yemen,1991,YEM,14430205,4.717444e+10,3269.15,NaN,NaN,22.70,56.68,9.99
8832,Yemen,1992,YEM,14989497,5.025991e+10,3353.01,NaN,NaN,22.70,56.68,9.99
8833,Yemen,1993,YEM,15563919,5.154868e+10,3312.06,NaN,NaN,22.70,56.68,9.99
8834,Yemen,1994,YEM,16149147,5.434118e+10,3364.96,NaN,NaN,22.70,56.68,9.99

In [ ]:
df_muro_oceania = df_muro_berlin[df_muro_berlin['country'].isin(oceania)]

In [ ]:
display(df_muro_oceania)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
364,Australia,1984,AUS,15620653,3.723796e+11,23838.93,NaN,NaN,5.64,25.30,19.43
365,Australia,1985,AUS,15835743,3.912293e+11,24705.46,1.00131,32.496351,5.99,25.52,19.27
366,Australia,1986,AUS,16069631,3.993444e+11,24850.88,NaN,NaN,6.37,26.29,18.89
367,Australia,1987,AUS,16322272,4.190940e+11,25676.21,NaN,NaN,7.51,27.87,18.26
368,Australia,1988,AUS,16594104,4.379128e+11,26389.66,NaN,NaN,9.22,29.48,17.83
...,...,...,...,...,...,...,...,...,...,...,...
8650,Vanuatu,1990,VUT,148073,NaN,NaN,NaN,NaN,10.42,36.34,20.76
8651,Vanuatu,1991,VUT,151807,NaN,NaN,NaN,NaN,10.70,36.65,20.75
8652,Vanuatu,1992,VUT,155619,NaN,NaN,NaN,NaN,10.96,36.95,20.75
8653,Vanuatu,1993,VUT,159475,NaN,NaN,NaN,NaN,11.22,37.25,20.75
8654,Vanuatu,1994,VUT,163328,NaN,NaN,NaN,NaN,11.47,37.53,20.74

In [ ]:
##################################################

In [13]:
### BLOQUES ECONÓMICOS ###

# MERCOSUR
mercosur = ['Argentina', 'Brazil', 'Paraguay', 'Uruguay', 'Venezuela']

# PAÍSES EMERGENTES
brics = ['Brazil', 'Russia', 'India', 'China', 'South Africa','Egypt', 'Ethiopia', 'Iran', 'United Arab Emirates']

# PETRÓLEO/ENERGÍA
medio_oriente = ['Bahrain', 'Iran', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon','Oman', 'Palestine', 'Qatar', 'Saudi Arabia', 'Syria','United Arab Emirates', 'Yemen']

# CLUB DE PAÍSES DESARROLLADOS
ocde = ['Austria', 'Belgium', 'Canada', 'Chile', 'Colombia', 'Czechia', 'Denmark','Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland','Ireland', 'Israel', 'Italy', 'Japan', 'South Korea', 'Latvia', 'Lithuania','Luxembourg', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Poland','Portugal', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland','Turkey', 'United Kingdom', 'United States', 'Australia']

# UNIÓN EUROPEA
union_europea = ['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden']

In [ ]:
df_muro_mercosur = df_muro_berlin[df_muro_berlin['country'].isin(mercosur)]

In [ ]:
display(df_muro_mercosur)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
274,Argentina,1984,ARG,29863090,3.578443e+11,11982.83,NaN,NaN,14.86,50.57,8.17
275,Argentina,1985,ARG,30336448,3.341714e+11,11015.51,NaN,NaN,14.86,50.57,8.17
276,Argentina,1986,ARG,30811982,3.586347e+11,11639.45,NaN,NaN,14.86,50.57,8.17
277,Argentina,1987,ARG,31291764,3.678936e+11,11756.88,NaN,NaN,14.86,50.57,8.17
278,Argentina,1988,ARG,31780534,3.609212e+11,11356.67,NaN,NaN,14.86,50.57,8.17
279,Argentina,1989,ARG,32270958,3.385208e+11,10489.95,NaN,NaN,14.86,50.57,8.17
280,Argentina,1990,ARG,32755907,3.387511e+11,10341.68,NaN,NaN,14.86,50.57,8.17
281,Argentina,1991,ARG,33230293,3.760579e+11,11316.72,NaN,NaN,14.86,50.57,8.17
282,Argentina,1992,ARG,33693532,4.166798e+11,12366.76,NaN,NaN,14.86,50.57,8.17
283,Argentina,1993,ARG,34152719,4.447803e+11,13023.28,NaN,NaN,14.86,50.57,8.17
284,Argentina,1994,ARG,34613492,4.729268e+11,13663.08,NaN,NaN,14.86,50.57,8.17
1039,Brazil,1984,BRA,132658861,1.001891e+12,7552.39,36.943433,58.299118,27.24,58.61,9.12
1040,Brazil,1985,BRA,135515593,1.080097e+12,7970.28,32.419664,55.526423,27.24,58.61,9.12
1041,Brazil,1986,BRA,138336371,1.160963e+12,8392.32,16.679659,58.432895,27.24,58.61,9.12
1042,Brazil,1987,BRA,141104946,1.201713e+12,8516.45,25.504920,59.643149,27.24,58.61,9.12
1043,Brazil,1988,BRA,143826357,1.200535e+12,8347.11,28.141427,61.372298,27.24,58.61,9.12
1044,Brazil,1989,BRA,146502975,1.238775e+12,8455.63,25.651020,63.245785,27.24,58.61,9.12
1045,Brazil,1990,BRA,149143223,1.185475e+12,7948.57,30.337527,60.450876,27.24,58.61,9.12
1046,Brazil,1991,BRA,151724253,1.213090e+12,7995.36,NaN,NaN,27.24,58.61,9.12
1047,Brazil,1992,BRA,154275077,1.221829e+12,7919.80,29.404223,53.103417,27.24,58.61,9.12
1048,Brazil,1993,BRA,156794574,1.298221e+12,8279.76,28.199798,60.066897,27.24,58.61,9.12
1049,Brazil,1994,BRA,159265011,1.391784e+12,8738.79,NaN,NaN,27.24,58.61,9.12
6259,Paraguay,1984,PRY,3412939,1.764376e+10,5169.67,NaN,NaN,22.27,55.41,8.39
6260,Paraguay,1985,PRY,3510678,1.834296e+10,5224.91,NaN,NaN,22.27,55.41,8.39
6261,Paraguay,1986,PRY,3611474,1.835297e+10,5081.85,NaN,NaN,22.27,55.41,8.39
6262,Paraguay,1987,PRY,3714892,1.914967e+10,5154.84,NaN,NaN,22.27,55.41,8.39
6263,Paraguay,1988,PRY,3820551,2.036357e+10,5330.01,NaN,NaN,22.27,55.41,8.39
6264,Paraguay,1989,PRY,3927802,2.153553e+10,5482.84,NaN,NaN,22.27,55.41,8.39
6265,Paraguay,1990,PRY,4035752,2.219612e+10,5499.87,2.546746,40.837216,22.27,55.41,8.39
6266,Paraguay,1991,PRY,4144370,2.281509e+10,5505.08,NaN,NaN,22.27,55.41,8.39
6267,Paraguay,1992,PRY,4253608,2.329773e+10,5477.17,NaN,NaN,22.27,55.41,8.39
6268,Paraguay,1993,PRY,4362706,2.434270e+10,5579.72,NaN,NaN,22.27,55.41,8.39
6269,Paraguay,1994,PRY,4471423,2.518086e+10,5631.51,NaN,NaN,22.27,55.41,8.39
8554,Uruguay,1984,URY,3002495,2.648544e+10,8821.14,NaN,NaN,19.01,48.42,13.61
8555,Uruguay,1985,URY,3017044,2.680981e+10,8886.12,NaN,NaN,19.01,48.42,13.61
8556,Uruguay,1986,URY,3032846,2.918247e+10,9622.14,NaN,NaN,19.01,48.42,13.61
8557,Uruguay,1987,URY,3049896,3.141994e+10,10301.97,NaN,NaN,19.01,48.42,13.61
8558,Uruguay,1988,URY,3067957,3.146541e+10,10256.14,NaN,NaN,19.01,48.42,13.61
8559,Uruguay,1989,URY,3086254,3.182184e+10,10310.83,NaN,NaN,19.01,48.42,13.61
8560,Uruguay,1990,URY,3104404,3.204855e+10,10323.58,NaN,NaN,19.01,48.42,13.61
8561,Uruguay,1991,URY,3122357,3.306876e+10,10590.96,NaN,NaN,19.01,48.42,13.61
8562,Uruguay,1992,URY,3139704,3.559818e+10,11338.07,NaN,NaN,19.01,48.42,13.61
8563,Uruguay,1993,URY,3156351,3.647114e+10,11554.84,NaN,NaN,19.01,48.42,13.61
8564,Uruguay,1994,URY,3172839,3.903640e+10,12303.30,NaN,NaN,19.01,48.42,13.61
8734,Venezuela,1984,VEN,17008838,2.249559e+11,13225.82,NaN,NaN,22.27,55.41,8.39
8735,Venezuela,1985,VEN,17461433,2.255570e+11,12917.44,NaN,NaN,22.27,55.41,8.39
8736,Venezuela,1986,VEN,17923542,2.399572e+11,13387.82,NaN,NaN,22.27,55.41,8.39
8737,Venezuela,1987,VEN,18394970,2.483426e+11,13500.57,12.285000,53.447968,22.27,55.41,8.39
8738,Venezuela,1988,VEN,18871021,2.629601e+11,13934.60,NaN,NaN,22.27,55.41,8.39
8739,Venezuela,1989,VEN,19348925,2.403467e+11,12421.71,7.263963,43.775499,22.27,55.41,8.39
8740,Venezuela,1990,VEN,19827005,2.560785e+11,12915.64,NaN,NaN,22.27,55.41,8.39
8741,Venezuela,1991,VEN,20304898,2.821323e+11,13894.79,NaN,NaN,22.27,55.41,8.39
8742,Venezuela,1992,VEN,20780946,3.010554e+11,14487.09,6.884314,42.061281,22.27,55.41,8.39
8743,Venezuela,1993,VEN,21254525,3.032639e+11,14268.21,NaN,NaN,22.27,55.41,8.39
8744,Venezuela,1994,VEN,21725186,2.977286e+11,13704.31,NaN,NaN,22.27,55.41,8.39

In [14]:
df_muro_brics = df_muro_berlin[df_muro_berlin['country'].isin(brics)]

In [15]:
display(df_muro_brics)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
1039,Brazil,1984,BRA,132658861,1.001891e+12,7552.39,36.943433,58.299118,27.24,58.61,9.12
1040,Brazil,1985,BRA,135515593,1.080097e+12,7970.28,32.419664,55.526423,27.24,58.61,9.12
1041,Brazil,1986,BRA,138336371,1.160963e+12,8392.32,16.679659,58.432895,27.24,58.61,9.12
1042,Brazil,1987,BRA,141104946,1.201713e+12,8516.45,25.504920,59.643149,27.24,58.61,9.12
1043,Brazil,1988,BRA,143826357,1.200535e+12,8347.11,28.141427,61.372298,27.24,58.61,9.12
...,...,...,...,...,...,...,...,...,...,...,...
8425,United Arab Emirates,1990,ARE,1898220,4.064137e+10,21410.25,NaN,NaN,20.02,55.77,10.08
8426,United Arab Emirates,1991,ARE,2006630,NaN,NaN,NaN,NaN,20.02,55.77,10.08
8427,United Arab Emirates,1992,ARE,2114738,NaN,NaN,NaN,NaN,20.02,55.77,10.08
8428,United Arab Emirates,1993,ARE,2222098,5.514966e+10,24818.73,NaN,NaN,20.02,55.77,10.08
8429,United Arab Emirates,1994,ARE,2328191,6.465442e+10,27770.24,NaN,NaN,20.02,55.77,10.08

In [16]:
df_muro_medio_oriente = df_muro_berlin[df_muro_berlin['country'].isin(medio_oriente)]

In [17]:
display(df_muro_medio_oriente)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
544,Bahrain,1984,BHR,415164,2.965761e+09,7143.59,NaN,NaN,22.21,56.52,10.89
545,Bahrain,1985,BHR,430365,2.955779e+09,6868.08,NaN,NaN,22.21,56.52,10.89
546,Bahrain,1986,BHR,446290,3.024145e+09,6776.19,NaN,NaN,22.21,56.52,10.89
547,Bahrain,1987,BHR,462862,3.084997e+09,6665.05,NaN,NaN,22.21,56.52,10.89
548,Bahrain,1988,BHR,479931,3.193430e+09,6653.94,NaN,NaN,22.21,56.52,10.89
...,...,...,...,...,...,...,...,...,...,...,...
8830,Yemen,1990,YEM,13887863,4.497104e+10,3238.15,NaN,NaN,22.70,56.68,9.99
8831,Yemen,1991,YEM,14430205,4.717444e+10,3269.15,NaN,NaN,22.70,56.68,9.99
8832,Yemen,1992,YEM,14989497,5.025991e+10,3353.01,NaN,NaN,22.70,56.68,9.99
8833,Yemen,1993,YEM,15563919,5.154868e+10,3312.06,NaN,NaN,22.70,56.68,9.99
8834,Yemen,1994,YEM,16149147,5.434118e+10,3364.96,NaN,NaN,22.70,56.68,9.99

In [18]:
df_muro_ocde = df_muro_berlin[df_muro_berlin['country'].isin(ocde)]

In [19]:
display(df_muro_ocde)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
364,Australia,1984,AUS,15620653,3.723796e+11,23838.93,NaN,NaN,5.64,25.30,19.43
365,Australia,1985,AUS,15835743,3.912293e+11,24705.46,1.001310,32.496351,5.99,25.52,19.27
366,Australia,1986,AUS,16069631,3.993444e+11,24850.88,NaN,NaN,6.37,26.29,18.89
367,Australia,1987,AUS,16322272,4.190940e+11,25676.21,NaN,NaN,7.51,27.87,18.26
368,Australia,1988,AUS,16594104,4.379128e+11,26389.66,NaN,NaN,9.22,29.48,17.83
...,...,...,...,...,...,...,...,...,...,...,...
8515,United States,1990,USA,253373387,9.250378e+12,36508.88,0.497143,38.262486,NaN,NaN,NaN
8516,United States,1991,USA,256471424,9.224688e+12,35967.70,0.499387,38.044837,NaN,NaN,NaN
8517,United States,1992,USA,259606021,9.552659e+12,36796.75,0.497899,38.372794,NaN,NaN,NaN
8518,United States,1993,USA,262633229,9.814940e+12,37371.28,0.748369,40.363088,NaN,NaN,NaN
8519,United States,1994,USA,265474811,1.021120e+13,38463.93,0.747120,39.985380,NaN,NaN,NaN

In [20]:
df_muro_ue = df_muro_berlin[df_muro_berlin['country'].isin(union_europea)]

In [21]:
display(df_muro_ue)

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
409,Austria,1984,AUT,7560715,1.738659e+11,22995.96,NaN,NaN,9.14,31.40,23.11
410,Austria,1985,AUT,7564310,1.777606e+11,23499.91,NaN,NaN,9.15,31.43,23.04
411,Austria,1986,AUT,7569397,1.819330e+11,24035.33,NaN,NaN,9.16,31.43,22.97
412,Austria,1987,AUT,7574314,1.849934e+11,24423.79,NaN,NaN,9.15,31.60,23.58
413,Austria,1988,AUT,7585346,1.908460e+11,25159.82,NaN,NaN,9.19,31.48,23.78
...,...,...,...,...,...,...,...,...,...,...,...
7705,Sweden,1990,SWE,8558571,2.402340e+11,28069.41,NaN,NaN,8.15,26.55,26.73
7706,Sweden,1991,SWE,8616955,2.379501e+11,27614.18,NaN,NaN,8.11,27.16,26.27
7707,Sweden,1992,SWE,8667576,2.357569e+11,27199.86,0.243513,24.908733,7.85,26.79,26.45
7708,Sweden,1993,SWE,8718038,2.315584e+11,26560.84,NaN,NaN,8.61,27.70,26.06
7709,Sweden,1994,SWE,8780190,2.415243e+11,27507.87,NaN,NaN,10.90,30.58,24.84