In [1]:
from google.colab import files
uploaded = files.upload()

Saving steam_games_2026.csv to steam_games_2026.csv

In [2]:
import pandas as pd

df = pd.read_csv("steam_games_2026.csv")

In [3]:
df.head()

,AppID,Name,Release_Date,Primary_Genre,All_Tags,Price_USD,Discount_Pct,Review_Score_Pct,Total_Reviews,Steam_Deck_Status,Estimated_Owners,24h_Peak_Players
0,730,Counter-Strike 2,2012-08-21,Action,FPS;Shooter;Multiplayer;Competitive;Action;Tea...,0.00,0,83,4980365,Unknown,149410950,1013936
1,2868840,Slay the Spire 2,2026-03-05,Indie,Strategy;Roguelike;Card Game;Deckbuilding;Co-o...,24.99,0,97,49549,Unknown,1486470,0
2,3321460,Crimson Desert,2026-03-19,Action,Action;Open World;Singleplayer;Adventure;Comba...,69.99,0,0,0,Unknown,0,0
3,3065800,Marathon,2026-03-05,Action,Extraction Shooter;PvP;Multiplayer;Sci-fi;Shoo...,39.99,0,90,24360,Unknown,730800,0
4,3764200,Resident Evil Requiem,2026-02-26,Action,Survival Horror;Zombies;Horror;Third-Person Sh...,69.99,0,96,79667,Unknown,2390010,0

In [4]:
df_reviews = pd.DataFrame({
    'AppID': [3321460, 2767030, 3564740, 3280350, 2141910, 3224770, 1973530, 3513350, 2483190, 2073850, 4045750, 2139460, 2073620, 4025700, 1449850, 216150, 2074920, 1476970, 2948190, 799960, 2707930, 3347400, 2244210, 2624870, 1607250, 3357650, 2507950, 767560, 1451050, 2016590, 3557620, 767320, 3164330, 920562, 2325290, 2215200, 1343400, 3199170, 588430, 1818450, 1343370, 1289670, 3681810, 2426960, 202520, 202521, 202524, 203700, 203701, 203702, 204380, 204381, 204382, 204383, 204384, 204385, 204386, 204387, 204388, 208540, 208541, 208542, 208543, 208544, 208545, 208546, 222680, 238230, 2072560, 381710, 381711, 381712, 381713, 2524890, 3061570, 1419170, 1997040, 1282270, 2867470, 2832310, 3500390, 2333480, 3092660, 1335200, 1974050, 3768760, 1056640, 886250, 206480, 2918150, 1385290, 601510, 3825780, 1573360, 590830, 3949290, 2569510, 1258080, 1961460, 2886620, 3179050, 1954420],
    'Total_Reviews': [139164, 383373, 107952, 19339, 27971, 55190, 102687, 43814, 0, 265759, 243, 170006, 52548, 13090, 97944, 15121, 110454, 28480, 6705, 9177, 40728, 2953, 0, 4313, 25227, 22452, 180142, 29701, 125, 81825, 20279, 860, 9715, 115, 23092, 0, 26753, 18468, 80825, 97744, 20215, 8, 18800, 10154, 11, 12, 11, 14, 25, 7, 23, 13, 10, 9, 20, 18, 25, 16, 35, 9, 26, 7, 9, 54, 13, 26, 16, 21, 9797, 69, 61, 87, 42, 44878, 12570, 46984, 34557, 29438, 131, 175, 585, 2350, 4377, 19251, 20050, 0, 24473, 8352, 7776, 4572, 203, 44145, 330, 1250, 0, 126, 1437, 17751, 56577, 198, 172, 4506,]
})

In [5]:
reviews_map = df_reviews.set_index('AppID')['Total_Reviews']
reviews_zero = (df['Total_Reviews'] == 0)
appids_to_update = pd.Index(df.loc[reviews_zero, 'AppID'].dropna().astype(int)).intersection(reviews_map.index)
df.loc[df['AppID'].isin(appids_to_update) & reviews_zero, 'Total_Reviews'] = \
    df.loc[df['AppID'].isin(appids_to_update) & reviews_zero, 'AppID'].map(reviews_map)

In [6]:
df.loc[df['Estimated_Owners'] == 0, 'Estimated_Owners'] = df['Total_Reviews'] * 30

In [7]:
df['Total_Sales'] = df['Estimated_Owners']
df['Revenue'] = df['Total_Sales']*df['Price_USD']

In [9]:
condition1 = df['Total_Reviews'] != 0
Juegos_reviews_actualizado = df[condition1]
display(Juegos_reviews_actualizado.head(1000))

,AppID,Name,Release_Date,Primary_Genre,All_Tags,Price_USD,Discount_Pct,Review_Score_Pct,Total_Reviews,Steam_Deck_Status,Estimated_Owners,24h_Peak_Players,Total_Sales,Revenue
0,730,Counter-Strike 2,2012-08-21,Action,FPS;Shooter;Multiplayer;Competitive;Action;Tea...,0.00,0,83,4980365,Unknown,149410950,1013936,149410950,0.0
1,2868840,Slay the Spire 2,2026-03-05,Indie,Strategy;Roguelike;Card Game;Deckbuilding;Co-o...,24.99,0,97,49549,Unknown,1486470,0,1486470,37146885.3
2,3321460,Crimson Desert,2026-03-19,Action,Action;Open World;Singleplayer;Adventure;Comba...,69.99,0,0,139164,Unknown,4174920,0,4174920,292202650.8
3,3065800,Marathon,2026-03-05,Action,Extraction Shooter;PvP;Multiplayer;Sci-fi;Shoo...,39.99,0,90,24360,Unknown,730800,0,730800,29224692.0
4,3764200,Resident Evil Requiem,2026-02-26,Action,Survival Horror;Zombies;Horror;Third-Person Sh...,69.99,0,96,79667,Unknown,2390010,0,2390010,167276799.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1202200,Paleo Pines,2023-09-26,Adventure,Dinosaurs;Farming Sim;Exploration;Relaxing;Ind...,7.49,75,93,1921,Unknown,57630,50,57630,431648.7
996,2753970,MARVEL Cosmic Invasion,2025-12-01,Action,Beat 'em up;Arcade;Pixel Graphics;Superhero;Co...,29.99,0,90,1630,Unknown,48900,0,48900,1466511.0
997,1239080,Door Kickers 2: Task Force North,2025-02-10,Action,Tactical;Top-Down;Real Time Tactics;Real-Time ...,24.99,0,96,11539,Unknown,346170,505,346170,8650788.3
998,1302240,Labyrinthine,2023-08-18,Action,Horror;Online Co-Op;Co-op;Puzzle;Psychological...,9.99,0,70,13549,Unknown,406470,179,406470,4060635.3
999,917950,Vellum,2025-05-02,Action,Online Co-Op;Action Roguelike;Third-Person Sho...,11.99,40,90,1188,Unknown,35640,141,35640,427323.6

In [10]:
juegos_gratis = Juegos_reviews_actualizado[Juegos_reviews_actualizado['Price_USD'] == 0]
juegos_gratis.head(107)

,AppID,Name,Release_Date,Primary_Genre,All_Tags,Price_USD,Discount_Pct,Review_Score_Pct,Total_Reviews,Steam_Deck_Status,Estimated_Owners,24h_Peak_Players,Total_Sales,Revenue
0,730,Counter-Strike 2,2012-08-21,Action,FPS;Shooter;Multiplayer;Competitive;Action;Tea...,0.0,0,83,4980365,Unknown,149410950,1013936,149410950,0.0
7,1172470,Apex Legends™,2020-11-04,Action,Free to Play;Multiplayer;Battle Royale;FPS;Sho...,0.0,0,65,1577,Unknown,47310,124262,47310,0.0
13,2767030,Marvel Rivals,2024-12-05,Action,Free to Play;Multiplayer;Hero Shooter;Third-Pe...,0.0,0,68,383373,Unknown,11501190,106611,11501190,0.0
14,1222670,The Sims™ 4,2020-06-18,Adventure,Life Sim;Free to Play;Character Customization;...,0.0,0,79,82661,Unknown,2479830,25276,2479830,0.0
16,359550,Tom Clancy's Rainbow Six Siege,2015-12-01,Action,FPS;PvP;Multiplayer;Shooter;Tactical;eSports;C...,0.0,0,75,1234092,Unknown,37022760,51847,37022760,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,1258080,Shop Titans,2020-05-05,Adventure,Idler;Shop Keeper;Crafting;Medieval;Base Build...,0.0,0,70,17751,Unknown,532530,3279,532530,0.0
955,1961460,PROJECT: PLAYTIME,2022-12-12,Action,Multiplayer;Horror;Survival Horror;Online Co-O...,0.0,0,83,56577,Unknown,1697310,0,1697310,0.0
960,933110,Age of Empires III: Definitive Edition,2020-10-15,Strategy,Strategy;Base Building;RTS;Multiplayer;Militar...,0.0,0,89,36135,Unknown,1084050,3016,1084050,0.0
967,1049590,Eternal Return,2023-07-19,Indie,Free to Play;MOBA;Anime;Sexual Content;PvP;eSp...,0.0,0,67,107,Unknown,3210,12341,3210,0.0
974,1954420,Riichi City × Date A LiveⅤ,2022-09-08,Unknown,Sexual Content;Casual;Mahjong;Anime;Thriller;C...,0.0,0,35,4506,Unknown,135180,406,135180,0.0

In [11]:
ARPU_base = {"Action": 13, "Adventure": 9, "RPG": 20, "Strategy": 13, "Simulation": 8, "Casual": 6, "Massively Multiplayer": 22, "Indie": 7, "Sports": 11, "Racing": 9, "Unknown": 10}

In [12]:
Juegos_reviews_actualizado['ARPU'] = Juegos_reviews_actualizado['Primary_Genre'].map(ARPU_base)
free_games = (Juegos_reviews_actualizado['Price_USD'] == 0)
Juegos_reviews_actualizado.loc[free_games,'Revenue'] = Juegos_reviews_actualizado.loc[free_games,'Estimated_Owners'] * Juegos_reviews_actualizado.loc[free_games,'ARPU']

Juegos_reviews_actualizado.head(1000)

/tmp/ipykernel_20278/2098095080.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Juegos_reviews_actualizado['ARPU'] = Juegos_reviews_actualizado['Primary_Genre'].map(ARPU_base)

,AppID,Name,Release_Date,Primary_Genre,All_Tags,Price_USD,Discount_Pct,Review_Score_Pct,Total_Reviews,Steam_Deck_Status,Estimated_Owners,24h_Peak_Players,Total_Sales,Revenue,ARPU
0,730,Counter-Strike 2,2012-08-21,Action,FPS;Shooter;Multiplayer;Competitive;Action;Tea...,0.00,0,83,4980365,Unknown,149410950,1013936,149410950,1.942342e+09,13.0
1,2868840,Slay the Spire 2,2026-03-05,Indie,Strategy;Roguelike;Card Game;Deckbuilding;Co-o...,24.99,0,97,49549,Unknown,1486470,0,1486470,3.714689e+07,7.0
2,3321460,Crimson Desert,2026-03-19,Action,Action;Open World;Singleplayer;Adventure;Comba...,69.99,0,0,139164,Unknown,4174920,0,4174920,2.922027e+08,13.0
3,3065800,Marathon,2026-03-05,Action,Extraction Shooter;PvP;Multiplayer;Sci-fi;Shoo...,39.99,0,90,24360,Unknown,730800,0,730800,2.922469e+07,13.0
4,3764200,Resident Evil Requiem,2026-02-26,Action,Survival Horror;Zombies;Horror;Third-Person Sh...,69.99,0,96,79667,Unknown,2390010,0,2390010,1.672768e+08,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1202200,Paleo Pines,2023-09-26,Adventure,Dinosaurs;Farming Sim;Exploration;Relaxing;Ind...,7.49,75,93,1921,Unknown,57630,50,57630,4.316487e+05,9.0
996,2753970,MARVEL Cosmic Invasion,2025-12-01,Action,Beat 'em up;Arcade;Pixel Graphics;Superhero;Co...,29.99,0,90,1630,Unknown,48900,0,48900,1.466511e+06,13.0
997,1239080,Door Kickers 2: Task Force North,2025-02-10,Action,Tactical;Top-Down;Real Time Tactics;Real-Time ...,24.99,0,96,11539,Unknown,346170,505,346170,8.650788e+06,13.0
998,1302240,Labyrinthine,2023-08-18,Action,Horror;Online Co-Op;Co-op;Puzzle;Psychological...,9.99,0,70,13549,Unknown,406470,179,406470,4.060635e+06,13.0
999,917950,Vellum,2025-05-02,Action,Online Co-Op;Action Roguelike;Third-Person Sho...,11.99,40,90,1188,Unknown,35640,141,35640,4.273236e+05,13.0

In [14]:
import plotly.express as px

In [17]:
ventas_por_genero = Juegos_reviews_actualizado.groupby('Primary_Genre')['Revenue'].sum().reset_index()

fig_bar = px.bar(
    ventas_por_genero,
    x='Primary_Genre',
    y='Revenue',
    title='Ventas Totales por Género Principal',
    labels={'Primary_Genre': 'Género Principal', 'Revenue': 'Ventas Totales'},
    hover_data={'Revenue': ':.2s'}
)

fig_bar.update_layout(xaxis_title='Género Principal', yaxis_title='Ventas Totales')
fig_bar.show()

In [21]:
fig_pie = px.pie(
    ventas_por_genero,
    values='Revenue',
    names='Primary_Genre',
    title='Porcentaje de Ingresos por Género Principal',
    labels={'Primary_Genre': 'Género Principal', 'Revenue': 'Ingresos'},
    hole=0.0 # Optional: creates a donut chart
)

fig_pie.update_traces(textposition='inside', textinfo='percent+label')
fig_pie.show()

In [22]:
ventas_totales_por_genero = Juegos_reviews_actualizado.groupby('Primary_Genre')['Total_Sales'].sum().reset_index()

fig_bar_sales = px.bar(
    ventas_totales_por_genero,
    x='Primary_Genre',
    y='Total_Sales',
    title='Ventas Totales de Juegos por Género Principal',
    labels={'Primary_Genre': 'Género Principal', 'Total_Sales': 'Ventas Totales'},
    hover_data={'Total_Sales': ':.2s'}
)

fig_bar_sales.update_layout(xaxis_title='Género Principal', yaxis_title='Ventas Totales')
fig_bar_sales.show()

In [24]:
fig_pie_sales = px.pie(
    ventas_totales_por_genero,
    values='Total_Sales',
    names='Primary_Genre',
    title='Porcentaje de Ventas por Género Principal',
    labels={'Primary_Genre': 'Género Principal', 'Total_Sales': 'Ventas Totales'},
    hole=0.0 # Optional: creates a donut chart
)

fig_pie_sales.update_traces(textposition='inside', textinfo='percent+label')
fig_pie_sales.show()